= Phần 1
<phan-1>

== CREATE - Tạo Các Quan Hệ
<create-tao-cac-quan-he>

- RDBS: Microsoft SQL Server.

=== `SINHVIEN`
<sinhvien>

```sql
CREATE TABLE SINHVIEN (
    MSSV CHAR(8) PRIMARY KEY,
    TENSV NVARCHAR(30) NOT NULL,
    SODT VARCHAR(10) NOT NULL,
    LOP CHAR(10) NOT NULL,
    DIACHI NCHAR(50)
);
```

=== `DETAI`
<detai>

```sql
CREATE TABLE DETAI (
    MSDT CHAR(6) PRIMARY KEY,
    TENDT NVARCHAR(30) NOT NULL
);
```

=== `SV_DETAI`
<sv-detai>

```sql
CREATE TABLE SV_DETAI (
    MSSV CHAR(8),
    MSDT CHAR(6),
    PRIMARY KEY (MSSV, MSDT),
    CONSTRAINT FK_SV_DETAI_SV  FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    CONSTRAINT FK_SV_DETAI_DT  FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
```

=== `HOCHAM`
<hocham>

```sql
CREATE TABLE HOCHAM (
    MSHH INT PRIMARY KEY,
    TENHH NVARCHAR(20) NOT NULL
);
```

=== `GIAOVIEN`
<giaovien>

```sql
CREATE TABLE GIAOVIEN (
    MSGV INT PRIMARY KEY,
    TENGV NVARCHAR(30) NOT NULL,
    DIACHI NVARCHAR(50) NOT NULL,
    SODT VARCHAR(10) NOT NULL,
    MSHH INT NOT NULL,
    NAMHH SMALLDATETIME NOT NULL,
    CONSTRAINT FK_GV_HH  FOREIGN KEY (MSHH) REFERENCES HOCHAM(MSHH)
);
```

=== `HOCVI`
<hocvi>

```sql
CREATE TABLE HOCVI (
    MSHV INT PRIMARY KEY,
    TENHV NVARCHAR(20) NOT NULL
);
```

=== `CHUYENNGANH`
<chuyennganh>

```sql
CREATE TABLE CHUYENNGANH (
    MSCN INT PRIMARY KEY,
    TENCN NVARCHAR(30) NOT NULL
);
```

=== `GV_HV_CN`
<gv-hv-cn>

```sql
CREATE TABLE GV_HV_CN (
    MSGV INT,
    MSHV INT,
    MSCN INT,
    NAM SMALLDATETIME NOT NULL,
    PRIMARY KEY (MSGV, MSHV, MSCN),
    CONSTRAINT FK_GV_HV_CN_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    CONSTRAINT FK_GV_HV_CN_HV FOREIGN KEY (MSHV) REFERENCES HOCVI(MSHV),
    CONSTRAINT FK_GV_HV_CN_CN FOREIGN KEY (MSCN) REFERENCES CHUYENNGANH(MSCN)
);
```

=== `GV_HDDT`
<gv-hddt>

```sql
CREATE TABLE GV_HDDT (
    MSGV INT,
    MSDT CHAR(6),
    DIEM FLOAT NOT NULL,
    PRIMARY KEY (MSGV, MSDT),
    CONSTRAINT FK_GV_HDDT_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    CONSTRAINT FK_GV_HDDT_DT FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
```

=== `GV_PBDT`
<gv-pbdt>

```sql
CREATE TABLE GV_PBDT (
    MSGV INT,
    MSDT CHAR(6),
    DIEM FLOAT NOT NULL,
    PRIMARY KEY (MSGV, MSDT),
    CONSTRAINT FK_GV_PBDT_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    CONSTRAINT FK_GV_PBDT_DT FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
```

=== `GV_UVDT`
<gv-uvdt>

```sql
CREATE TABLE GV_UVDT (
    MSGV INT,
    MSDT CHAR(6),
    DIEM FLOAT NOT NULL,
    PRIMARY KEY (MSGV, MSDT),
    CONSTRAINT FK_GV_UVDT_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    CONSTRAINT FK_GV_UVDT_DT FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
```

=== `HOIDONG`
<hoidong>

```sql
CREATE TABLE HOIDONG (
    MSHD INT PRIMARY KEY,
    PHONG INT NOT NULL,
    TGBD SMALLDATETIME NOT NULL,
    NGAYHD SMALLDATETIME NOT NULL,
    TINHTRANG NVARCHAR(30),
    MSGV INT,
    CONSTRAINT FK_HD_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV)
);
```

=== `HOIDONG_GV`
<hoidong-gv>

```sql
CREATE TABLE HOIDONG_GV (
    MSHD INT,
    MSGV INT,
    PRIMARY KEY (MSHD, MSGV),
    CONSTRAINT FK_HD_GV_HD FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
    CONSTRAINT FK_HD_GV_GV FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV)
);
```

=== `HOIDONG_DT`
<hoidong-dt>

```sql
CREATE TABLE HOIDONG_DT (
    MSHD INT,
    MSDT CHAR(6),
    QUYETDINH NCHAR(10),
    CONSTRAINT PK_HD_DT PRIMARY KEY (MSHD, MSDT),
    CONSTRAINT FK_HD_DT_HD FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
    CONSTRAINT FK_HD_DT_DT FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
```

== INSERT - Thêm Dữ Liệu
<insert-them-du-lieu>

- RDBS: Microsoft SQL Server.

=== Table `SINHVIEN`
<table-sinhvien>

```sql
```

=== Table `DETAI`
<table-detai>

```sql
```

=== Table `SV_DETAI`
<table-sv-detai>


=== Table `HOCHAM`
<table-hocham>


=== Table `GIAOVIEN`
<table-giaovien>


=== Table `HOCVI`
<table-hocvi>


=== Table `CHUYENNGANH`
<table-chuyennganh>


=== Table `GV_HV_CN`
<table-gv-hv-cn>


=== Table `GV_HDDT`
<table-gv-hddt>


=== Table `GV_PBDT`
<table-gv-pbdt>


=== Table `GV_UVDT`
<table-gv-uvdt>


=== Table `HOIDONG`
<table-hoidong>


=== Table `HOIDONG_GV`
<table-hoidong-gv>


=== Table `HOIDONG_DT`
<table-hoidong-dt>
