direction: right

# --- 0. STYLES ---
style: {
  opacity: 0.0
  fill: transparent
  font-size: 30
}

# --- 1. SETTINGS ---
classes: {
  entity: {
    shape: rectangle
    style: {border-radius: 10; fill: "#FFFFFF"; stroke: "#333333"; font-size: 30}
  }
  rel: {
    shape: diamond
    style: {fill: "#F2F2F7"; stroke: "#8E8E93"; font-size: 30}
  }
  attr: {
    shape: oval
    # width: 100; height: 50
    style: {fill: "#F0F8FF"; stroke: "#4682B4"; stroke-dash: 3}
  }
  attr_pri: {
    shape: oval
    style: {
      fill: "#F0F8FF"
      stroke: "#0d95de"
      stroke-width: 1
      underline: true
    }
  }
}

# --- 2. ENTITIES ---
ADMINS: {class: entity; label: "ADMINS"}
# admin_id: {class: attr_pri; label: "ID Admin"}
# ADMINS -- admin_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

DATPHONG: {class: entity; label: "DATPHONG"}
# datphong_id: {class: attr_pri; label: "ID Đặt Phòng"}
# DATPHONG -- datphong_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

DICHVU: {class: entity; label: "DICHVU"}
# dichvu_id: {class: attr_pri; label: "ID Dịch Vụ"}
# DICHVU -- dichvu_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

LOAIPHONG: {class: entity; label: "LOAIPHONG"}
# loaiphong_id: {class: attr_pri; label: "ID Loại Phòng"}
# LOAIPHONG -- loaiphong_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

PAYMENTS: {class: entity; label: "PAYMENTS"}
# payments_id: {class: attr_pri; label: "ID Thanh Toán"}
# PAYMENTS -- payments_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

PERMISSIONS: {class: entity; label: "PERMISSIONS"}
# permissions_id: {class: attr_pri; label: "ID Quyền Hạn"}
# PERMISSIONS -- permissions_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

PHONG: {class: entity; label: "PHONG"}
# phong_id: {class: attr_pri; label: "ID Phòng"}
# PHONG -- phong_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

REFUNDS: {class: entity; label: "REFUNDS"}
# refunds_id: {class: attr_pri; label: "ID Hoàn Tiền"}
# REFUNDS -- refunds_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

REVIEWS: {class: entity; label: "REVIEWS"}
# reviews_id: {class: attr_pri; label: "ID Đánh Giá"}
# REVIEWS -- reviews_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

ROLES: {class: entity; label: "ROLES"}
# roles_id: {class: attr_pri; label: "ID Vai Trò"}
# ROLES -- roles_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

USERS: {class: entity; label: "USERS"}
# users_id: {class: attr_pri; label: "ID Người Dùng"}
# USERS -- users_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

VOUCHERS: {class: entity; label: "VOUCHERS"}
# vouchers_id: {class: attr_pri; label: "ID Voucher"}
# VOUCHERS -- vouchers_id: {style: {stroke: "#0d95de"; stroke-width: 1}}

# --- 3. RELATIONSHIPS ---
# ngôn ngữ "tự nhiên"

# ADMINS -> REFUNDS: duyệt (1-n)
# Admins có thể duyệt tối thiểu 0 và tối đa n lần hoàn tiền.
# Một hoàn tiền có và chỉ có 1 admin duyệt.
admins_refunds: {class: rel; label: "duyệt"}
ADMINS -- admins_refunds: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
admins_refunds -- REFUNDS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# ADMINS -> ROLES: được cấp (n-n)
# n - n: viền cam
# Một admin phải có tối thiểu 1 và tối đa n role được gán.
# Một role có tối thiểu 0 và tối đa n admin được gán.
admins_roles: {class: rel; label: "được cấp"; style: {stroke: orange}}
ADMINS -- admins_roles: {target-arrowhead.label: "(1, n)"; style: {font-size: 30}}
admins_roles -- ROLES: {source-arrowhead.label: "(0, n)"; style: {font-size: 30}}

# DATPHONG -> DICHVU: sử dụng (n-n)
# Một đơn đặt phòng có thể có tối thiểu 0 và tối đa n dịch vụ đi kèm.
# Một dịch vụ đi kèm có thể được sử dụng tối thiểu 0 và tối đa n đơn đặt phòng.
datphong_dichvu: {class: rel; label: "sử dụng"; style: {stroke: orange}}
DATPHONG -- datphong_dichvu: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
datphong_dichvu -- DICHVU: {source-arrowhead.label: "(0, n)"; style: {font-size: 30}}

# DATPHONG -> PAYMENTS: được (1-n)
# Một đơn đặt phòng có tối thiểu 0 và tối đa n thanh toán.
# Một thanh toán có và chỉ có 1 đơn đặt phòng.
datphong_payments: {class: rel; label: "được"}
DATPHONG -- datphong_payments: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
datphong_payments -- PAYMENTS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# DATPHONG -> PHONG: bao gồm (1-n)
# Một đơn đặt phòng có tối thiểu 1 và tối đa n phòng.
# Một phòng có tối thiểu 0 và tối đa n đơn đặt phòng.
datphong_phong: {class: rel; label: "bao gồm"; style: {stroke: orange}}
DATPHONG -- datphong_phong: {target-arrowhead.label: "(1, n)"; style: {font-size: 30}}
datphong_phong -- PHONG: {source-arrowhead.label: "(0, n)"; style: {font-size: 30}}

# DATPHONG -> REVIEWS: được (1-1)
# Một đơn đặt phòng có tối thiểu 0 và tối đa 1 đánh giá.
# Một đánh giá thuộc và chỉ thuộc 1 đơn đặt phòng.
datphong_reviews: {class: rel; label: "được"}
DATPHONG -- datphong_reviews: {target-arrowhead.label: "(0, 1)"; style: {font-size: 30}}
datphong_reviews -- REVIEWS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# LOAIPHONG <- PHONG: thuộc
# Một loại phòng có tối thiểu 0 và tối đa n phòng.
# Một phòng thuộc và chỉ thuộc 1 loại phòng.
loaiphong_phong: {class: rel; label: "bao gồm"}
LOAIPHONG -- loaiphong_phong: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
loaiphong_phong -- PHONG: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# PAYMENTS -> REFUNDS: được
# Một thanh toán có tối thiểu 0 và tối đa n hoàn tiền.
# Một hoàn tiền được và chỉ được tạo từ 1 thanh toán.
payments_refunds: {class: rel; label: "được"}
PAYMENTS -- payments_refunds: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
payments_refunds -- REFUNDS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# ROLES -> PERMISSIONS: có gán (n-n)
# Một vai trò có tối thiểu 0 và tối đa n quyền hạn.
# Một quyền hạn có tối thiểu 0 và tối đa n vai trò.
roles_permissions: {class: rel; label: "có gán"; style: {stroke: orange}}
ROLES -- roles_permissions: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
roles_permissions -- PERMISSIONS: {source-arrowhead.label: "(0, n)"; style: {font-size: 30}}

# USERS -> DATPHONG: thực hiện (1-n)
# Một user có tối thiểu 0, và tối đa n đặt phòng
# Một đặt phòng có và chỉ có 1 user
users_datphong: {class: rel; label: "thực hiện"}
USERS -- users_datphong: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
users_datphong -- DATPHONG: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# USERS -> PAYMENTS: thực hiện (1-n)
# Một user có tối thiểu 0, và tối đa n thanh toán.
# Một thanh toán có và chỉ có 1 user
users_payment: {class: rel; label: "thực hiện"}
USERS -- users_payment: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
users_payment -- PAYMENTS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# USERS -> REFUNDS: yêu cầu (1-n)
# Một user có tối thiểu 0, và tối đa n yêu cầu hoàn tiền.
# Một yêu cầu hoàn tiền có và chỉ có 1 user.
users_refunds: {class: rel; label: "yêu cầu"}
USERS -- users_refunds: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
users_refunds -- REFUNDS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# USERS -> REVIEWS: viết (1-n)
# Một user có tối thiểu 0, và tối đa n đánh giá.
# Một đánh giá có tối thiểu 1 tối đa 1 user.
users_reviews: {class: rel; label: "viết"}
USERS -- users_reviews: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
users_reviews -- REVIEWS: {source-arrowhead.label: "(1, 1)"; style: {font-size: 30}}

# VOUCHERS -> DATPHONG: áp dụng (1-n)
# Một mã giảm giá có tối thiểu 0, và tối đa n đơn đặt phòng.
# Một đơn đặt phòng có tối thiểu 0, và tối đa 1 mã giảm giá áp dụng.
vouchers_datphong: {class: rel; label: "áp dụng"}
VOUCHERS -- vouchers_datphong: {target-arrowhead.label: "(0, n)"; style: {font-size: 30}}
vouchers_datphong -- DATPHONG: {source-arrowhead.label: "(0, 1)"; style: {font-size: 30}}

# 4. Bảng Số
# Tách riêng cho dễ cập nhật và quản lý.
