---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Duolingo"))
    ("Học Ngôn Ngữ")
      Toàn cầu
      Hàng triệu người dùng
      Hàng trăm ngôn ngữ
    (Mô hình AI "Birdbrain")
      Cá nhân hóa độ khó của bài học.
      Xây dựng hành trình học tập phù hợp.
    ("Explain My Answer")
      Giải thích lỗi sai.
      Mô phỏng vai trò của giáo viên.