---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Phụ Thuộc Dữ Liệu và Rủi Ro #quot;Ảo Giác#quot; AI"))
    "Kết quả phụ thuộc hoàn toàn dữ liệu đầu vào."
    "Rủi ro định kiến hoặc sai lệch."
    "Cách trình bày tự tin, thuyết phục."
    "Nhạy cảm: Y Tế, Pháp Lý, Tài Chính."