---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)**LỢI ÍCH ĐỊNH LƯỢNG**(
  ((**Tăng Năng Suất**))
    (Tối ưu đầu ra trên mỗi đơn vị đầu vào)
    Hoàn thành công việc nhanh hơn.
    Loại bỏ hoặc giảm bớt tác vụ lặp lại.
    Tăng hiệu quả lao động.