---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Xây Dựng Văn Hóa Số Và Đạo Đức AI"))
    Sử dụng AI có trách nhiệm.
      Mỗi cá nhân và tổ chức đều có trách nhiệm.
    Kiến thức về An toàn thông tin.
      Không chia sẻ thông tin bừa bãi.
      Sử dụng mạng xã hội có chọn lọc.
    Bộ Quy Tắc Ứng Xử với AI.
      Dùng khi nào, thế nào.
    Nguyên tắc *Human in the loop*.
      Con người đưa ra quyết định cuối cùng.