---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Thay Đổi Văn Hóa Và Mô Hình Vận Hành Tổ Chức<br/>Xây dựng #quot;Văn Hóa Số#quot;:"))
    "Hình thành các quy tắc ứng xử mới."
    "Nâng cao kỹ năng phản biện."
    "Tổ chức trở nên minh bạch và chuyên nghiệp hơn."