---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Tự Động Hóa và Tối Ưu Hóa Không Gian Sống))
  (**Tự Động**)
    Bật đèn khi mở cửa.
    Điều chỉnh nhiệt độ phòng vào ban đêm.
    Tắt các thiết bị điện khi không có người trong nhà.
  (**Tối Ưu**)
    Sử dụng năng lượng.
    Sử dụng thời gian.
    Sử dụng tài nguyên.