---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)Vai Trò & Ý Nghĩa của Ứng Dụng AI(
  {{fa:fa-chart-bar <br> **LỢI ÍCH ĐỊNH LƯỢNG**}}
    ((fa:fa-rocket <br> **Tăng Năng Suất** <br> Tối ưu đầu ra trên mỗi đơn vị đầu vào))
    ((fa:fa-chart-line <br> **Tăng Trưởng Kinh Tế** <br> Thúc đẩy GDP và mở rộng thị trường))
    ((fa:fa-piggy-bank <br> **Tiết Kiệm Chi Phí** <br> Cắt giảm lãng phí và chi phí vận hành))