---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("TikTok"))
    ((Real-time Loop"))
      (Phản hồi thời gian thực.)
      (Phân tích nội dung video **thị giác, âm thanh**)
      (Ưu tiên "tỉ lệ hoàn thành".)
      (Điều chỉnh luồng nội dung "Dành Cho Bạn" ngay lập tức.)
      (Vòng lặp liên tục dựa trên sở thích của người dùng.)