---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)Cá Nhân Hóa Hành Trình Mua Sắm(
  (Công nghệ gợi ý)
    (AI như một tư vấn viên chuyên nghiệp.)
    (Tăng mức độ hài lòng.)
  (Phân tích lịch sử)
    (Tìm kiếm)
    (Mua hàng)
    (Các hành vi tương tác.)
  (Đề xuất sản phẩm phù hợp.)
    (Giảm thời gian tìm kiếm.)
    (Phát hiện xu hướng, sở thích.)