---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Mục Tiêu"))
    ("Hệ thống tự thực hiện các tác vụ thông minh")
    ("Học tập, suy luận và giải quyết vấn đề.")
    ("Nhận thức, ra quyết định và cảm xúc.")