---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Tự Động Hóa Tác Vụ Tri Thức"))
    "Tích hợp Generative AI vào các công cụ văn phòng."
        "Microsoft Office: Copilot."
        "Google Workspace: Gemini"
        "Các bộ suite đầy đủ: Gemini Enterprise."