---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("**Smart Home**"))
    "**Tự động hóa**"
        "Bật đèn khi mở cửa."
        "Điều chỉnh nhiệt độ phòng vào ban đêm."
        "Tắt các thiết bị điện khi không có người trong nhà."
    "**Tối ưu hóa**"
        "Sử dụng năng lượng."
        "Sử dụng thời gian."
        "Sử dụng tài nguyên."