---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((**Từ "Ra Lệnh" sang "Cộng Tác"**))
  {{**Ra Lệnh ~ Phản Hồi**}}
    1~ Mô hình truyền thống.
    2~ "Cầm tay chỉ việc".
    3~ Máy không hiểu ngữ cảnh.
    4~ Thông tin đưa vào rời rạc qua các prompts.
  {{**Định Hướng ~ Cộng Tác**}}
    1~ Tin tưởng & phân quyền.
    2~ Người: Chỉ định mục tiêu.
    3~ AI: Hiểu ngữ cảnh.
    4~ AI: Lên kế hoạch và thực hiện.