---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Zing MP3"))
    Ứng dụng nghe nhạc hàng đầu Việt Nam.
    ("Daily Mix")
        Theo lịch sử nghe nhạc hoặc sở thích.
        Gợi ý theo tâm trạng "mood-based".
    ("Quan Trọng")
        Phân tích đặc trưng âm thanh của nhạc Việt.
