---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI-assisted Career Profiling"))
    "Xây dựng hồ sơ năng lực cá nhân."
    "Đề xuất lộ trình phát triển sự nghiệp."
    "Kết nối với các cơ hội việc làm phù hợp."