---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Tại Sao Lại Là Lúc Này?<br/>Hội tụ của các yếu tố sau:"))
    "Toán Học: Các lý thuyết Đại số tuyến tính, Xác Suất, Tối ưu hóa."
    "Dữ Liệu: Sự bùng nổ của Internet, Big Data."
    "Hạ Tầng: Cloud, Data Center, HPC, GPU, TPU, NPU."