---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Tìm Kiếm Và Thử Nghiệm Trực Quan"))
    "Tìm Kiếm Bằng Hình Ảnh."
        "Upload hình ảnh sản phẩm."
        "Tìm kiếm sản phẩm chính xác hoặc tương tự."
    "Thử Đồ Ảo **Virtual Try-on**."
        "Thực tế ảo tăng cường **AR**."
        "#quot;Thử#quot; sản phẩm vào thực tế bản thân hoặc không gian riêng."
    "Dự Báo Xu Hướng."
        "Gợi ý các sản phẩm #quot;hot trend#quot;."
        "Luôn bắt kịp xu hướng."