---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Lumi, Rạng Đông và FPT"))
    "**FPT**"
        "**FPT Smart Home**"
            "Điều khiển thông minh thông qua giọng nói."
            "FPT Play: #quot;Trái tim#quot;, kết hợp giải trí và điều khiển SmartHome."