---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Nâng Cao Chất Lượng Sống và An Toàn Cho Con Người"))
    "**Camera thông minh**"
        "Nhận diện khuôn mặt"
            "Ngăn chặn người lạ."
        "Phát hiện chuyển động hoặc hành vi bất thường."
            "Cảnh báo nguy hiểm."
    "**Cảm biến thông minh**"
        "Phát hiện rò rỉ khí gas, khói, cháy nổ hoặc nước tràn."
            "Tự động ngắt nguồn điện."
            "Gửi thông báo khẩn cấp."