---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Sportify"))
    "#quot;Dailylist#quot;"
        "Thay đổi tiêu đề & nội dung theo tâm trạng."
    "#quot;AI DJ#quot;"
        "Giọng nói AI để dẫn chuyện, chia sẻ thông tin bài hát/nghệ sĩ."
        "Như một chương trình phát thanh cá nhân hóa."