---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI Là Gì?"))
    ((Mục Tiêu))
        ("Hệ thống tự thực hiện các tác vụ thông minh.")
        ("Học tập, suy luận và giải quyết vấn đề.")
        ("Nhận thức, ra quyết định và cảm xúc.")
    ((Lịch Sử))
        ("Khởi nguồn từ đầu thế kỷ 20")
        ("Bùng nổ mạnh mẽ và ứng dụng sâu rộng vào thế kỷ 21.")
    ((Tại Sao Lại Là Lúc Này?))
        (Toán Học)
            "Các lý thuyết Đại Số Tuyến Tính, Xác Suất, Tối ưu hóa."
        (Dữ Liệu)
            "Sự bùng nổ của Internet, Big Data."
        (Hạ Tầng)
            "Cloud, Data Center"
            "HPC, GPU, TPU, NPU."