---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Chatbot CSKH))
  {{Tương tác Tự động 24/7}}
    (Cầu nối giao tiếp quan trọng)
    (Thay đổi cách thức chăm sóc và hỗ trợ khách hàng.)
  {{Khả năng phản hồi tức thì}}
    24/7, có hoặc không cần giám sát
    Thường làm *front-line* cho nhân sự con người
  {{Hỗ trợ đa ngôn ngữ}}
    Vượt qua rào cản ngôn ngữ
    Tự động nhận diện hoặc chỉ định
  {{Thấu hiểu ngữ cảnh}}
    Phân tích tình huống, biểu cảm
    Xem xét thông tin liên quan
      Tình trạng đơn hàng
      Lịch sử tương tác trước đó