---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)**LỢI ÍCH ĐỊNH LƯỢNG**(
  ((**Tăng Trưởng Kinh Tế**))
    Thúc đẩy GDP và mở rộng thị trường
    Hạ giá thành sản phẩm.
    Tăng biên lợi nhuận.
    Tái đầu tư cho nghiên cứu và mở rộng sản xuất.