---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("TikTok"))
    "#quot;Real-time Loop#quot;: Phản hồi thời gian thực."
        "Phân tích nội dung video **thị giác, âm thanh**"
        "Ưu tiên #quot;tỉ lệ hoàn thành#quot;."
            "Điều chỉnh luồng nội dung #quot;Dành Cho Bạn#quot; ngay lập tức."
            "Vòng lặp liên tục dựa trên sở thích của người dùng."