---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((**Nâng Cao Chất Lượng Sống và <br>An Toàn Cho Con Người**))
  (**Camera Thông Minh**)
    (Nhận Diện Khuôn Mặt)
      Ngăn chặn người lạ.
    (Phát Hiện Chuyển Động Hoặc Hành Vi Bất Thường.)
      Cảnh báo nguy hiểm.
  (**Cảm Biến Thông Minh**)
    (Phát Hiện Bất Thường)
      Rò rỉ khí gas, khói, cháy nổ hoặc nước tràn.
    (Thực Hiện Hành Động)
      Tự động ngắt nguồn điện.
      Gửi thông báo khẩn cấp.