---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Sự Tiến Hóa của Không Gian Sống Thông Minh"))
    "Không gian sống thông minh."
    "Có khả năng học hỏi, dự đoán và thích nghi với nhu cầu của con người."
    "Thay đổi cách con người sống và tương tác với không gian."