---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI Phản Ánh Con Người và Xã Hội"))
    "AI phản ánh nhu cầu và tâm lý của con người."
    "Quan trọng hơn, AI sẽ khuếch đại các yếu tố đó một cách mạnh mẽ."
    "Đây là một vòng lặp liên tục và khép kín."