---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Ưu Tiên Phát Triển Năng Lực Con Người Và Kỹ Năng AI"))
    Các chương trình đào tạo diện rộng về AI
      Tư duy dữ liệu
      Kỹ năng sử dụng cho nhiều tầng lớp
    Tập trung kỹ năng "con Người"
      Giao tiếp
      Sáng tạo
      Phản biện
      Giải quyết vấn đề
    Cách phối hợp và làm việc với AI
      Hợp Tác
      Đồng Hành
    Chương trình "Đào tạo lại"
      Những kỹ năng hoặc công việc mới
      Cho các nhân sự bị ảnh hưởng