---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root((**Agentic Workflows**))
    (1. Nhận Xét)
      Là xu hướng chung nổi bật.
      Tiến tới tự động hóa hoàn toàn bởi Agents.
    (2. Các Tác Nhân AI "Agents" Hợp Tác)
      Giải thích các đoạn mã nguồn.
      Tự động tạo mã nguồn.
      Phát hiện lỗi.
      Tối ưu mã nguồn.
    (3. Hành Vi Của Agents)
      Tự động lên kế hoạch và hoàn thành yêu cầu.
      Có thể hoặc không yêu cầu xét duyệt từ con người.
    (4. Lợi Ích)
      Tăng tốc độ và chất lượng phát triển phần mềm.
      Con người tập trung hơn vào phần core business.