---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Tìm Kiếm Và Thử Nghiệm Trực Quan))
  (Tìm Kiếm Bằng Hình Ảnh)
    Upload hình ảnh sản phẩm
    Tìm kiếm sản phẩm chính xác hoặc tương tự
  (Thử Đồ Ảo **Virtual Try-on**)
    Thực tế ảo tăng cường **AR**
    Thử sản phẩm vào thực tế bản thân
    Hoặc thử với không gian riêng
  (Dự Báo Xu Hướng)
    Gợi ý các sản phẩm *hot trend*
    Luôn bắt kịp nhu cầu