---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Xây Dựng Khung Quản Trị Và Pháp Lý Cho AI"))
    (Bảo vệ dữ liệu cá nhân)
      Thu thập
      Làm sạch
      Lưu trữ
      Mã hóa
    (Minh bạch thuật toán)
      Các white paper và research paper
      Trình bày cách hoạt động và dữ liệu đầu vào
    (Trách nhiệm pháp lý)
      Cá nhân vs Tổ chức
      Mức độ vi phạm và hình phạt
    (Đánh giá tác động xã hội)
      Đặc biệt là trẻ em
      Những người dễ tổn thương cả về tâm lý và hoàn cảnh
    (Sử dụng AI an toàn và có trách nhiệm)
      Luôn luôn và liên tục
      Trách nhiệm chung của tất cả mọi cá nhân và tổ chức
      Sử dụng các quy định hoặc giáo dục