---
config:
  theme: mc
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
{{**Ra Lệnh ~ Phản Hồi**}}
  1~ Mô hình truyền thống.
  2~ "Cầm tay chỉ việc".
  3~ Máy không hiểu ngữ cảnh.
  4~ Thông tin đưa vào rời rạc qua các prompts.