---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Các Nền Tảng Thực Tế))
  ((TopCV Việt Nam))
    TopCV là một nền tảng tuyển dụng trực tuyến hàng đầu tại Việt Nam.
    TopCV AI để phân tích sâu hồ sơ ứng viên và hành vi tìm việc.
    Chấm điểm độ phù hợp của hồ sơ so với bản mô tả công việc.
    Sàng lọc các ứng viên tiềm năng trong số hàng ngàn hồ sơ.
  ((JobHopin))
    Phân tích dữ liệu thị trường lao động theo thời gian thực.
    Đưa ra báo cáo về mức lương, xu hướng kỹ năng.
    Quản lý nhân tài và kết nối với các cơ hội việc làm phù hợp.