---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("**Smart Home**"))
    ((Tự Động và Tối Ưu Không Gian Sống))
    ((Nâng Cao Chất Lượng Sống và An Toàn Cho Con Người))
    ((Không Gian Sống Thông Minh))