---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Xây Dựng Văn Hóa Số Và Đạo Đức AI"))
    "Sử dụng AI có trách nhiệm."
    "Kiến thức về An toàn thông tin."
    "#quot;Bộ Quy Tắc Ứng Xử với AI#quot;."
        "Dùng khi nào, thế nào."
    "Nguyên tắc #quot;Human in the loop#quot;."