---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Netflix - Kẻ Dẫn Đầu))
  {{Dynamic Optimizer}}
    Tối ưu từng khung hình.
    Điều chỉnh chất lượng nén dựa trên bối cảnh của phim, băng thông mạng.
    Đem đến trải nghiệm mượt mà.
  {{Dynamic Thumbnail}}
    Tạo thumbnail động của phim dựa trên sở thích của người xem.
    Cùng một bộ phim nhưng mỗi người sẽ thấy thumbnail khác nhau.
      Tương ứng mối quan tâm hoặc sở thích của người đó.
    Tăng tỷ lệ click **CTR** và thời gian xem.
    Người dùng được trải nghiệm đa dạng khía cạnh của nội dung.