---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)YouTube - Mạng Thần Kinh Đa Tầng(
  {{Neural Networks}}
  ((Dự đoán bạn muốn xem gì))
    (Gợi ý nội dung tương tự)
  ((Tối ưu *thời gian xem chất lượng*.))
    (Lọc nội dung phù hợp.)
    (Chấm điểm tương tác.)
  ((Dẫn dắt xu hướng.))
    (*Đọc được suy nghĩ* của người xem.)