---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Xây Dựng Khung Quản Trị Và Pháp Lý Cho AI"))
    "Bảo vệ dữ liệu cá nhân."
    "Minh bạch thuật toán."
    "Trách nhiệm pháp lý."
    "Đánh giá tác động xã hội."
    "Sử dụng AI an toàn và có trách nhiệm."