---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  (AI Trong Tuyển Dụng & Nhân Sự)
    (("AI-assisted Career Profiling"))
        Xây dựng hồ sơ năng lực cá nhân
        Đề xuất lộ trình phát triển sự nghiệp
        Kết nối với các cơ hội việc làm phù hợp
    (("AI-powered Recruitment"))
        Tự động sàng lọc hồ sơ ứng viên
        Đánh giá kỹ năng và kinh nghiệm
        Phỏng vấn tự động và đánh giá hành vi
    (("AI-driven Employee Development"))
        Cá nhân hóa lộ trình đào tạo
        Đề xuất khóa học và tài liệu học tập
        Đánh giá hiệu quả đào tạo và phát triển