---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Tác Động Đến Việc Làm và Kỹ Năng Lao Động"))
    "Nhiều công việc bị tự động hóa nhanh."
    "Người lao động không bắt kịp các kỹ năng mới."
    "Gây tình trạng: thừa người - thiếu kỹ năng."
    "Cần có kế hoạch đào tạo, nâng cấp rõ ràng."