---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("VioEdu"))
    ("EdTech của Việt Nam.")
    ("**Knowledge Graph**")
      Mô hình Cây Kiến Thức
    ("Phân tích lỗi sai")
      a. Xác định lỗ hổng kiến thức.
      b. Đề xuất lộ trình học tập phù hợp