---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Lumi, Rạng Đông và FPT"))
    "**Lumi Việt Nam**"
        "Tự nhận biết trời tối để đóng rèm, bật đèn."
        "Điều chỉnh nhiệt độ điều hòa phù hợp."
        "Tự nhận biết thời tiết để điều chỉnh nhiệt độ."
    "**Rạng Đông**"
        "**RalliSmart**"
            "#quot;Chiếu sáng vì sức khỏe#quot; **Human Centric Lighting**"
            "Điều chỉnh phổ ánh sáng và cường độ theo nhịp sinh học."
            "Mô phỏng ánh sáng tự nhiên."