---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Xu Hướng Chung: Agentic Workflows"))
    "Các Tác Nhân AI **Agents** Cùng Hợp Tác"
        "Giải thích các đoạn mã nguồn."
        "Tự động tạo mã nguồn."
        "Phát hiện lỗi."
        "Tối ưu mã nguồn."
    "Tự động lên kế hoạch và hoàn thành yêu cầu."
    "Tăng tốc độ và chất lượng phát triển phần mềm."