---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Chatbot CSKH và Tương tác Tự động 24/7<br/>Cầu nối giao tiếp quan trọng, thay đổi cách thức chăm sóc và hỗ trợ khách hàng."))
    "Khả năng phản hồi tức thì."
        "24/7, có hoặc không cần giám sát."
    "Hỗ trợ đa ngôn ngữ."
        "Vượt qua rào cản ngôn ngữ."
    "Thấu hiểu ngữ cảnh."
        "Phân tích cảm xúc, ý định."