---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)**LỢI ÍCH ĐỊNH LƯỢNG**(
  ((**Tiết Kiệm Chi Phí**))
    Cắt giảm lãng phí và chi phí vận hành
    (Tự động hóa các quy trình rập khuôn.)
    (Tối ưu tài nguyên & quy trình.)
    (Giảm sai sót do con người.)