---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Lumi, Rạng Đông và FPT"))
    ("**Lumi Việt Nam**")
      "Tiên Phong" tại Việt Nam từ 2012
      Tự nhận biết trời tối để đóng rèm, bật đèn.
      Điều chỉnh nhiệt độ điều hòa phù hợp thói quen.
    ("**Rạng Đông**")
      ("**RalliSmart**")
        "#quot;Chiếu sáng vì sức khỏe#quot; **Human Centric Lighting**"
        Điều chỉnh phổ ánh sáng và cường độ theo nhịp sinh học.
        Mô phỏng ánh sáng tự nhiên.
    ("**FPT**")
      ("**FPT Smart Home**")
        Điều khiển thông minh thông qua giọng nói.
      ("**FPT Play Box**")
        "Trái tim" của hệ thống Smart Home.
        Kết hợp giải trí và điều khiển SmartHome.