---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((AI Trong Di Chuyển và Giao Thông))
  (Bản Đồ và Chỉ Đường)
    Google Maps, Waze
    Dự đoán tình hình giao thông.
    Tính toán lộ trình tối ưu.
    Hoàn thành trong thời gian thực.
  (Ứng Dụng Đặt Xe)
    Grab, Be
    Tìm kiếm xe gần nhất.
    Dự đoán thời gian đáp ứng.
  (Xe Tự Lái - Tự Hành.)
    Nhận diện chướng ngại vật, khoảng cách các xe.
    Tự di chuyển hoặc tự đỗ xe.
    Tesla Auto Pilot
  Hệ Thống ADAS
    **Advanced Driver Assistance Systems**
    Hỗ trợ người lái
    Tăng mức độ an toàn cho hành trình
