---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Người Đồng Hành, Không Phải Người Thay Thế"))
    ("AI không nhằm thay thế")
      (Giáo Viên)
      (Giảng Viên)
      Giáo viên là người truyền cảm hứng, định hướng, và phát triển kỹ năng cá nhân.
    ("Đồng hành - Tăng tốc")
      Quá trình học tập
      Rèn luyện kỹ năng
    (Giúp Mở rộng, Khai triển)
      Khả năng đã có.
      Ý tưởng mới.