---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Ưu Tiên Phát Triển Năng Lực Con Người Và Kỹ Năng AI"))
    "Các chương trình đào tạo diện rộng về AI."
    "Tư duy dữ liệu, kỹ năng sử dụng cho nhiều tầng lớp."
    "Tập trung kỹ năng #quot;con Người#quot;: giao tiếp, sáng tạo, phản biện."
    "Cách phối hợp và làm việc với AI."
    "Chương trình #quot;Đào tạo lại#quot; cho các nhân sự có công việc bị ảnh hưởng."