---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI-driven Employee Development"))
    "Cá nhân hóa lộ trình đào tạo."
    "Đề xuất khóa học và tài liệu học tập."
    "Đánh giá hiệu quả đào tạo và phát triển."