---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Quyền Riêng Tư, Bảo Vệ Dữ Liệu và Niềm Tin Số"))
    (Dữ Liệu Cá Nhân)
      Thu thập, lưu trữ và phân tích lượng lớn
      Thường không rõ hoặc không thể biết dữ liệu được quản lý thế nào.
    (Nguy Cơ)
      Nguy cơ rò rỉ, mua bán dữ liệu.
      Tạo điều kiện cho các hình thức lừa đảo.
    (Hệ Quả)
      Gây mất niềm tin xã hội
      Thậm chí các nguy hiểm.