---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Duolingo"))
    "Toàn cầu, hàng triệu người dùng, hàng trăm ngôn ngữ."
    "Mô hình AI #quot;Birdbrain#quot;."
        "Cá nhân hóa độ khó của bài học."
    "#quot;Explain My Answer#quot;:"
        "Giải thích lỗi sai."
        "Mô phỏng vai trò của giáo viên."