---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Thao Túng Thông Tin, Deepfake và Xói Mòn Nhận Thức Xã Hội"))
    (Video, hình ảnh, giọng nói giả dạng)
      Dễ phát tán và tràn lan
      Làm mờ ranh giới và khó phân biệt thật giả
    (Nguy Cơ)
      Lừa đảo, tống tiền và các tệ nạn khác
      Gây giảm năng lực tư duy phản biện và đối thoại
    (Hệ Quả)
      Ảnh hưởng trực tiếp đến niềm tin xã hội
      Tâm lý lo lắng và suy giảm sự tin tưởng vào con người