---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Sportify"))
    ("Dailylist")
      Trending hoặc sở thích.
      Thay đổi chủ đề & nội dung theo tâm trạng.
    ("AI DJ")
      Giọng nói AI để dẫn chuyện, chia sẻ thông tin bài hát/nghệ sĩ.
      Như một chương trình phát thanh cá nhân hóa.