---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Nâng Cao Chất Lượng Sống và An Toàn Cho Con Người"))
    "**Trợ Lý Cá Nhân**"
        "Theo dõi thói quen sinh hoạt."
        "Nhận diện bất thường hoặc tình huống khẩn cấp."
        "Đề xuất giải pháp."