---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((AI Như Các Cộng Sự Số))
  (Tích Hợp Sâu Vào Không Gian Làm Việc)
    Microsoft Office: Copilot
    Google Workspace: Gemini
    Các bộ suite đầy đủ: Gemini Enterprise
  (Tự Động Hóa Tác Vụ Tri Thức)
    Viết bản nháp email, báo cáo, trình chiếu trong vài giây.
    Tổng hợp thông tin từ tài liệu nội bộ.
    Tóm tắt cuộc họp hoặc các văn bản dài.
    Phân tích dữ liệu hoặc báo cáo.
  (Trợ Lý Thông Minh)
    "Hỏi gì - Đáp nấy"
    Hiểu nhiều loại dữ liệu - multimodal.
    "Thông thạo" nhiều ngôn ngữ.
    Tạo ra nội dung sáng tạo: Hình ảnh, video, âm nhạc.