---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("JobHopin"))
    "Phân tích dữ liệu thị trường lao động theo thời gian thực."
    "Đưa ra báo cáo về mức lương, xu hướng kỹ năng."
    "Quản lý nhân tài và kết nối với các cơ hội việc làm phù hợp."