---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI Không Còn Là Lý Thuyết Hay Tương Lai Xa"))
    "AI đã và đang hiện hữu trong đời sống hàng ngày."
    "Từ cuộc sống đến công việc."
    "Từ Giải Trí đến Học Tập."
    "Từ Giao Thông đến Mua Sắm."