---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((AI Hiện Hữu Quanh Chúng Ta))
  (AI đã và đang hiện hữu trong đời sống hàng ngày.)
  (Từ Cuộc Sống đến Công Việc.)
  (Từ Giải Trí đến Học Tập.)
  (Từ Giao Thông đến Mua Sắm.)
  (Từ Y tế đến Giáo dục.)