---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
((Elsa Speak))
  Ứng dụng học tiếng Anh toàn cầu.
  (Công nghệ nhận diện giọng nói độc quyền)
    Phân tích phát âm.
    (Chỉ ra lỗi sai cụ thể)
      Cách uốn lưỡi
      Âm gió
  (Cá Nhân Hóa)
    Trình độ hiện tại
    Lộ trình học
    Mức độ luyện tập
  (Gia Sư Ảo)
    Thực hành hội thoại tự do "role-play"
    (Mô phỏng tình huống thực tế)
      Xin việc
      Gọi món
      Chào hỏi