---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Hệ Sinh Thái Matter và Google/Amazon"))
    "**Matter**"
        "Hệ sinh thái IoT toàn diện."
        "Chuẩn hóa và tương thích nhiều nhà cung cấp."
    "Sản phẩm:"
        "Google Nest"
        "Amazon Echo"