---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Elsa Speak"))
    "Ứng dụng học tiếng Anh toàn cầu."
    "Công nghệ nhận diện giọng nói độc quyền và phân tích phát âm."
    "Chỉ ra lỗi sai cụ thể: cách uốn lưỡi, âm gió, vv.."
    "#quot;Gia sư ảo#quot;: thực hành hội thoại tự do **role-play**"
        "Mô phỏng tình huống thực tế **xin việc, gọi món, vv..**"