---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
)**LỢI ÍCH ĐỊNH TÍNH**(
  ((**Củng Cố Niềm Tin + Sự An Tâm**))
    ((**Dự Báo Chủ Động**))
        Dự báo và phòng ngừa rủi ro từ sớm.
        Phát hiện các gian lận tài chính hay email spam thời gian thực.
    ((**Edge AI**))
      Thông tin được lưu trữ ngay tại thiết bị biên edge.
      Dữ liệu không rời thiết bị hoặc không gian của người dùng.
