---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("Cá nhân hóa Hành trình và Công cụ Gợi ý"))
    "AI như một tư vấn viên chuyên nghiệp."
    "Phân tích lịch sử tìm kiếm, mua hàng, các hành vi tương tác."
    "Phát hiện xu hướng, sở thích."
    "Đề xuất sản phẩm phù hợp."
        "Giảm thời gian tìm kiếm."
        "Tăng mức độ hài lòng."