---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("AI Là Hiện Tại, Xu Thế và Tương Lai"))
    "Các công cụ AI trong Cuộc Sống & Công Việc sẽ còn phát triển hơn nữa."
    "Dần trở thành một phần tất yếu, tương tự như Điện, Internet, vv.."
    "Học cách Sử Dụng và Hợp Tác với AI là điều xã hội mới cần có."