---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
  root(("VioEdu"))
    "EdTech Việt Nam."
    "#quot;Cây kiến thức#quot; **Knowledge Graph**"
    "Phân tích lỗi sai $\rightarrow$ Xác định lỗ hổng kiến thức."
    "Đề xuất lộ trình học tập phù hợp."