---
config:
  theme: redux-color
  themeVariables:
    fontFamily: Google Sans
    fontSize: 20px
---
mindmap
root((fa:fa-chart-bar <br/> **LỢI ÍCH ĐỊNH LƯỢNG**))
  (fa:fa-rocket <br/> **Tăng Năng Suất**)
    Tối ưu đầu ra trên mỗi đơn vị đầu vào
  (fa:fa-chart-line <br/> **Tăng Trưởng Kinh Tế**)
    Thúc đẩy GDP và mở rộng thị trường
  (fa:fa-piggy-bank <br/> **Tiết Kiệm Chi Phí**)
    Cắt giảm lãng phí và chi phí vận hành